### ISSUE TITLE
Project 1 - Personal Portfolio

### ISSUE THREAD

**Issue by camerican** [camerican/NYCDA_SCC16_Kamila#6]
The Personal Portfolio has the following requirements:
- [x] At least 3 separate pages +
- [ ] Connected by a consistent navigation menu (3)
- [ ] Uses CSS layout principles, with design-friendly whitespace (6)
- [x] Includes images (2)
- [ ] Has links to external websites that open in a new window
- [x] Incorporates a ul and nav powered navigation bar (2)
- [ ] Overall quality of the site (3)
- [x] Is well committed and pushed to GitHub (3)

It would be great to invest some time to make sure that the portfolio meets all those requirements above.
- [x] Clean up project file structure (#7)
- [x] Ensure that the menu appears consistently across all pages (#8)
- [ ] day4.html appears blank (#9)
- [ ] "2 Column" menu option links to something called try.html (#10)
- [ ] External links are missing (#11)
- [ ] More detailed GitHub commits required (#13)
- [ ] Whitespace and layout could use tuning (#12)

**Comment by camerican** [comment]
Hi Kamila,

The decode images were not included in the repository, so are all missing:

![screen shot 2016-08-29 at 12 05 23 pm](https://cloud.githubusercontent.com/assets/2566680/18058684/7dc83942-6de3-11e6-9f99-61c99e895ea7.png)

There's also a layout issue where your bullets are trapped underneath an image:

![screen shot 2016-08-29 at 12 05 41 pm](https://cloud.githubusercontent.com/assets/2566680/18058698/8e86c2c6-6de3-11e6-9cd3-f2a0ed8dd2ac.png)

You might try treating that situation with margin-right on the image or padding-left on the `li`

The image gallery navigation menu is not displaying as an inline-block, which deviates from other pages:

![screen shot 2016-08-29 at 12 06 01 pm](https://cloud.githubusercontent.com/assets/2566680/18058727/b40add34-6de3-11e6-955e-7f9b91720dc7.png)

**Comment by camerican** [comment]
On your decode page you're using only placeholder text and those columns are overlapping:

![screen shot 2016-08-29 at 12 05 50 pm](https://cloud.githubusercontent.com/assets/2566680/18058783/e7fcf136-6de3-11e6-82b8-670920d0ff2c.png)
